# Generated by Codex on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocation",
            name="is_sharing_live",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="stopped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
