# Generated by Django 5.2.12 on 2026-04-04 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=64)),
                ('is_checked', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['user', 'category', 'sort_order'], name='checklist_p_user_id_611223_idx'), models.Index(fields=['user', 'is_checked'], name='checklist_p_user_id_2e65a4_idx')],
            },
        ),
    ]
