# Generated by Django 5.0.1 on 2026-03-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bounding_box', models.JSONField()),
                ('size_mb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trail_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='routes_mapr_name_537f96_idx')],
            },
        ),
    ]
