# Generated by Django 5.0.1 on 2026-03-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=50)),
                ('elevation_gain_m', models.PositiveIntegerField()),
                ('geojson', models.JSONField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='routes.mapregion')),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='routes_trai_region__e68932_idx'), models.Index(fields=['difficulty'], name='routes_trai_difficu_ae40f9_idx')],
            },
        ),
    ]
