# Generated by Django 5.0.1 on 2026-04-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupmembership_role'),
        ('routes', '0002_trail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], max_length=16)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('technical', 'Technical')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='groups.group')),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_routes', to='routes.trail')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['group', 'status'], name='routes_user_group_i_a79737_idx'), models.Index(fields=['created_by'], name='routes_user_created_047e0f_idx'), models.Index(fields=['trail'], name='routes_user_trail_i_9d2551_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('day_number', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('waypoint_type', models.CharField(choices=[('campsite', 'Campsite'), ('teahouse', 'Teahouse'), ('checkpoint', 'Checkpoint'), ('rest_stop', 'Rest Stop'), ('emergency_point', 'Emergency Point'), ('trailhead', 'Trailhead')], max_length=24)),
                ('is_emergency_point', models.BooleanField(default=False)),
                ('estimated_duration_from_prev', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='routes.userroute')),
            ],
            options={
                'ordering': ['day_number', 'order', 'id'],
                'indexes': [models.Index(fields=['route', 'day_number', 'order'], name='routes_rout_route_i_a39437_idx'), models.Index(fields=['waypoint_type'], name='routes_rout_waypoin_e62d85_idx')],
            },
        ),
    ]
