CHECKLIST_CATEGORY_ORDER = [
    'Safety',
    'Clothing',
    'Food and Water',
    'Navigation',
    'Shelter',
    'Medical',
    'Documents',
    'Electronics',
    'Miscellaneous',
]

DEFAULT_PACKING_ITEMS = [
    {'category': 'Safety', 'name': 'Headlamp', 'note': 'Pack spare batteries if using replaceable cells.'},
    {'category': 'Safety', 'name': 'Whistle', 'note': 'Keep it accessible on your pack strap.'},
    {'category': 'Safety', 'name': 'Emergency blanket', 'note': 'Lightweight backup for sudden weather shifts.'},
    {'category': 'Clothing', 'name': 'Rain jacket', 'note': 'Waterproof outer layer.'},
    {'category': 'Clothing', 'name': 'Base layer', 'note': 'Dry change for camp or cold mornings.'},
    {'category': 'Clothing', 'name': 'Warm hat and gloves', 'note': 'Essential for higher elevations.'},
    {'category': 'Food and Water', 'name': 'Water bottles or hydration bladder', 'note': 'Carry enough capacity for your route.'},
    {'category': 'Food and Water', 'name': 'Trail snacks', 'note': 'High-energy food for quick breaks.'},
    {'category': 'Food and Water', 'name': 'Water purification method', 'note': 'Filter, tablets, or purifier.'},
    {'category': 'Navigation', 'name': 'Offline map', 'note': 'Download the area before leaving coverage.'},
    {'category': 'Navigation', 'name': 'Compass', 'note': 'Backup navigation if devices fail.'},
    {'category': 'Navigation', 'name': 'Route notes or itinerary', 'note': 'Keep key checkpoints handy.'},
    {'category': 'Shelter', 'name': 'Tent or shelter', 'note': 'Match shelter to the trip plan.'},
    {'category': 'Shelter', 'name': 'Sleeping bag', 'note': 'Check the temperature rating.'},
    {'category': 'Shelter', 'name': 'Sleeping pad', 'note': 'Adds warmth and recovery comfort.'},
    {'category': 'Medical', 'name': 'First aid kit', 'note': 'Restock essentials before each trip.'},
    {'category': 'Medical', 'name': 'Personal medication', 'note': 'Check expiry dates.'},
    {'category': 'Medical', 'name': 'Blister care supplies', 'note': 'Tape, pads, or skin protection.'},
    {'category': 'Documents', 'name': 'ID or permit', 'note': 'Carry required entry or trek permits.'},
    {'category': 'Documents', 'name': 'Emergency contacts', 'note': 'Keep a written copy.'},
    {'category': 'Documents', 'name': 'Insurance details', 'note': 'Useful for remote or high-risk routes.'},
    {'category': 'Electronics', 'name': 'Phone', 'note': 'Charge fully before departure.'},
    {'category': 'Electronics', 'name': 'Power bank', 'note': 'Bring the cable you need.'},
    {'category': 'Electronics', 'name': 'Charging cable', 'note': 'Include wall adapter if relevant.'},
    {'category': 'Miscellaneous', 'name': 'Sunscreen', 'note': 'High SPF for exposed trails.'},
    {'category': 'Miscellaneous', 'name': 'Lip balm', 'note': 'Helpful in dry or windy conditions.'},
    {'category': 'Miscellaneous', 'name': 'Toilet paper or tissue', 'note': 'Pack out waste when required.'},
]

