# Generated by Codex on 2026-04-02

from itertools import combinations

from django.db import migrations


def bootstrap_user_connections(apps, schema_editor):
    GroupMembership = apps.get_model('groups', 'GroupMembership')
    UserConnection = apps.get_model('users', 'UserConnection')

    group_members = {}
    for group_id, user_id in GroupMembership.objects.values_list('group_id', 'user_id'):
        group_members.setdefault(group_id, set()).add(user_id)

    shared_pairs = set()
    for member_ids in group_members.values():
        for first_user_id, second_user_id in combinations(sorted(member_ids), 2):
            shared_pairs.add((first_user_id, second_user_id))

    existing_pairs = set()
    for from_user_id, to_user_id in UserConnection.objects.values_list('from_user_id', 'to_user_id'):
        existing_pairs.add(tuple(sorted((from_user_id, to_user_id))))

    new_connections = []
    for first_user_id, second_user_id in shared_pairs:
        pair = (first_user_id, second_user_id)
        if pair in existing_pairs:
            continue
        existing_pairs.add(pair)
        new_connections.append(
            UserConnection(
                from_user_id=first_user_id,
                to_user_id=second_user_id,
                status='accepted',
            )
        )

    if new_connections:
        UserConnection.objects.bulk_create(new_connections)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_activity_fields'),
        ('users', '0005_userconnection'),
    ]

    operations = [
        migrations.RunPython(bootstrap_user_connections, noop_reverse),
    ]
