# Generated by Codex on 2026-04-03

from django.db import migrations, models


def assign_group_owner_roles(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')
    GroupMembership = apps.get_model('groups', 'GroupMembership')

    for group in Group.objects.all().only('id', 'created_by_id'):
        GroupMembership.objects.filter(
            group_id=group.id,
            user_id=group.created_by_id,
        ).update(role='owner')


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_bootstrap_user_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(
                choices=[('owner', 'Owner'), ('member', 'Member')],
                default='member',
                max_length=16,
            ),
        ),
        migrations.RunPython(assign_group_owner_roles, noop_reverse),
    ]
